image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deply-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/service-business-statistic-1.0.0-SNAPSHOT.jar
    expire_in: 1 hrs

docker-build:
  stage: docker-build
  script:
    - docker 2>/dev/null 1>&2 rmi `docker images -aq` || true
    - docker build -t $CI_DOCKER_LOGIN/service-business-statistic .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/service-business-statistic

docker-deply-swarm:
  stage: docker-deply-swarm
  script:
    - touch .env_bstat
    - echo "POSTGRES_USER=admin" >> .env_bstat
    - echo "POSTGRES_PASS=admin" >> .env_bstat
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env_bstat
    - echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env_bstat
    - echo "SPRING_PROFILE=$SPRING_PROFILE" >> .env_bstat
    - echo "RABBIT_HOST=rabbitmq" >> .env_bstat
    - echo "RABBIT_PORT=5672" >> .env_bstat
    - echo "RABBIT_USER=admin" >> .env_bstat
    - echo "RABBIT_PASS=2b01db35ec69408aa65276dd710bc99c" >> .env_bstat
    - docker stack deploy -c docker-compose.yaml socshared




