spring:
  datasource:
    url:  jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
jpa:
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    hbm2ddl:
      auto: create

service:
  stat:
    kde-h: 0.3337
    kde_estimate_size: 200
  news:
    tracking_num_days: 3
    number_of_checks_per_day: 50