server:
  port: 8884

spring:
  datasource:
    url:  jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:bstat}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost} # RabbitMQ host.
    password: ${RABBIT_PASS:mqadmin} # Login to authenticate against the broker.
    port: ${RABBIT_PORT:5672} # RabbitMQ port.
    username: ${RABBIT_USER:mqadmin} # Login user to authenticate to the broker.

feign:
  url:
    auth: ${AUTH_SERVICE:http://auth-service:9999}
    storage: ${STORAGE_SERVICE:http://storage-service:8686}

service:
  news:
    tracking_num_days: 3