server:
  port: 8884

spring:
  datasource:
    url:  jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:bstat}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true

feign:
  url:
    auth: ${AUTH_SERVICE:http://auth-service:9999}

service:
  news:
    tracking_num_days: 3
    number_of_checks_per_day: 50