spring:
  datasource:
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
jpa:
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    hbm2ddl:
      auto: create
    rabbitmq:
      host: ${RABBIT_HOST:localhost} # RabbitMQ host.
      password: ${RABBIT_PASS:mqadmin} # Login to authenticate against the broker.
      port: ${RABBIT_PORT:5672} # RabbitMQ port.
      username: ${RABBIT_USER:mqadmin} # Login user to authenticate to the broker.

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}
    storage: ${STORAGE_SERVICE:https://storage.socshared.ml}


service:
  news:
    tracking_num_days: 3