server:
  port: 8884

spring:
  datasource:
    url:  jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:bstat}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    hbm2ddl:
      auto: create

service:
  news:
    tracking_num_days: 3
    number_of_checks_per_day: 50